2024-TikiTaka/be-triptroop

src/main/java/com/tikitaka/triptroop/travel/controller/TravelController.java, src/main/java/com/tikitaka/triptroop/travel/domain/entity/Travel.java, src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelRepository.java, src/main/java/com/tikitaka/triptroop/travel/domain/type/TravelType.java, src/main/java/com/tikitaka/triptroop/travel/dto/request/TravelRequest.java, src/main/java/com/tikitaka/triptroop/travel/dto/response/TravelResponse.java, src/main/java/com/tikitaka/triptroop/travel/service/TravelService.java
=> #2 여행 소개 패키지

src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java, src/main/java/com/tikitaka/triptroop/schedule/domain/entity/Schedule.java, src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepository.java, src/main/java/com/tikitaka/triptroop/schedule/domain/type/ScheduleType.java, src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleRequest.java, src/main/java/com/tikitaka/triptroop/schedule/dto/response/ScheduleResponse.java, src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
일정 패키지 작성
- 일정 패키지 작성
- 
- Close #1
=> 1# 일정 패키지 작성

src/main/java/com/tikitaka/triptroop/chat/controller/ChatController.java, src/main/java/com/tikitaka/triptroop/chat/domain/entity/Chat.java, src/main/java/com/tikitaka/triptroop/chat/domain/repository/ChatRepository.java, src/main/java/com/tikitaka/triptroop/chat/dto/request/ChatRequest.java, src/main/java/com/tikitaka/triptroop/chat/dto/response/ChatResponse.java, src/main/java/com/tikitaka/triptroop/chat/service/ChatService.java
=> #7 채팅 패키지 작성

src/main/java/com/tikitaka/triptroop/common/config/BeanConfig.java, src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java, src/main/resources/ddl.sql
>  DDL 수정 및 Configuration 추가
-  #18
- `ddl.sql` 수정: likes 테이블의 kind 값이 지정되어 있지 않았음
- `BeanConfig` 추가: PasswordEncoder 분리
=> #18 DDL 수정 및 Configuration 추가

src/main/resources/create.sql, src/main/resources/insert.sql
> create, insert 문 작성 
- #18
- `ddl.sql` -> `create.sql`로 rename
- `create.sql`에 AUTO_INCREMENT, UNIQUE 제약조건 추가
- 회원, 카테고리, 지역 관련 `insert.sql` 작성
create, insert 문 실행해주세요
=> #18 create, insert 문 작성

.gitignore, src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java, src/main/java/com/tikitaka/triptroop/common/domain/type/StatusType.java, src/main/resources/create.sql
> SecurityConfig 임시 설정 적용
- #18
- SecurityConfig 설정: request 경로와 cors 임시 해제
- StatusType 삭제
=> #18 SecurityConfig 임시 설정 적용

Dockerfile, src/main/resources/create.sql
>  Dockerfile 추가 및 테이블 수정
- closed #18
- `Dockerfile` 추가 
- `create.sql` 수정 : `schedule` 테이블의 `kind` 길이 수정
=> #18 Dockerfile 추가 및 테이블 수정

src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java, src/main/java/com/tikitaka/triptroop/schedule/domain/entity/ScheduleItem.java, src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleItemRepository.java, src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleCreateRequest.java, src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleItemCreateRequest.java, src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
일정 계획 등록 기능 추가 
#23
일정 계획 등록 기능 추가
=> #23 일정 계획 등록 추가

src/main/java/com/tikitaka/triptroop/common/domain/entity/BaseTimeEntity.java, src/main/java/com/tikitaka/triptroop/image/domain/entity/Image.java, src/main/java/com/tikitaka/triptroop/image/domain/repository/ImageRepository.java, src/main/java/com/tikitaka/triptroop/image/service/ImageService.java, src/main/java/com/tikitaka/triptroop/travel/controller/TravelController.java, src/main/java/com/tikitaka/triptroop/travel/domain/entity/Travel.java, src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelRepository.java, src/main/java/com/tikitaka/triptroop/travel/dto/request/TravelRequest.java, src/main/java/com/tikitaka/triptroop/travel/service/TravelService.java
- closed #5
- 여행소개조회 , 여행소개 등록 기능 구현
=> #5 여행지소개 조회, 이미지 등록 기능 구현

src/main/java/com/tikitaka/triptroop/friend/controller/FriendController.java, src/main/java/com/tikitaka/triptroop/friend/domain/entity/Friend.java, src/main/java/com/tikitaka/triptroop/friend/domain/repository/FriendRepository.java, src/main/java/com/tikitaka/triptroop/friend/domain/type/Friend.java, src/main/java/com/tikitaka/triptroop/friend/dto/request/FriendRequest.java, src/main/java/com/tikitaka/triptroop/friend/dto/response/FriendResponse.java, src/main/java/com/tikitaka/triptroop/friend/service/FriendService.java
> 친구 도메인 패키지 작성
- closed #{이슈번호}
- 추가된 내용 또는 변경 사항에 대한 상세내역을 작성해주세요.
=> #44 친구 도메인 패키지 작성

src/main/java/com/tikitaka/triptroop/place/domain/entity/Place.java, src/main/java/com/tikitaka/triptroop/place/domain/repository/PlaceRepository.java, src/main/java/com/tikitaka/triptroop/place/dto/PlaceDto.java, src/main/java/com/tikitaka/triptroop/place/dto/request/PlaceRequest.java, src/main/java/com/tikitaka/triptroop/place/service/PlaceService.java, src/main/java/com/tikitaka/triptroop/travel/controller/TravelController.java, src/main/java/com/tikitaka/triptroop/travel/domain/entity/Travel.java, src/main/java/com/tikitaka/triptroop/travel/domain/entity/TravelComment.java, src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelRepository.java, src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelRepositoryCustom.java, src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelRepositoryImpl.java, src/main/java/com/tikitaka/triptroop/travel/dto/TravelCommentsDto.java, src/main/java/com/tikitaka/triptroop/travel/dto/response/TravelDetailResponse.java, src/main/java/com/tikitaka/triptroop/travel/dto/response/TravelResponse.java, src/main/java/com/tikitaka/triptroop/travel/service/TravelService.java, src/main/java/com/tikitaka/triptroop/travelLong/controller/TravelLogController.java, src/main/java/com/tikitaka/triptroop/travelLong/controller/TravelLogItemController.java, src/main/java/com/tikitaka/triptroop/travelLong/domain/entity/TravelLog.java, src/main/java/com/tikitaka/triptroop/travelLong/domain/entity/TravelLogItem.java, src/main/java/com/tikitaka/triptroop/travelLong/domain/repository/TravelLogRepository.java, src/main/java/com/tikitaka/triptroop/travelLong/domain/type/TravelLogType.java, src/main/java/com/tikitaka/triptroop/travelLong/dto/request/TravelLogItemRequest.java, src/main/java/com/tikitaka/triptroop/travelLong/dto/request/TravelLogRequest.java, src/main/java/com/tikitaka/triptroop/travelLong/dto/response/TravelLogItemResponse.java, src/main/java/com/tikitaka/triptroop/travelLong/dto/response/TravelLogResponse.java, src/main/java/com/tikitaka/triptroop/travelLong/service/TravelLogItemService.java, src/main/java/com/tikitaka/triptroop/travelLong/service/TravelLogService.java
=> #43 여행소개 상세페이지 기능추가 

.gitmodules, src/main/java/com/tikitaka/triptroop/common/exception/type/ExceptionCode.java, src/main/java/com/tikitaka/triptroop/common/security/handler/LoginFailureHandler.java, src/main/java/com/tikitaka/triptroop/user/AuthController/AuthController.java, src/main/java/com/tikitaka/triptroop/user/controller/AuthController.java, src/main/java/com/tikitaka/triptroop/user/controller/ProfileController.java, src/main/java/com/tikitaka/triptroop/user/controller/UserController.java, src/main/java/com/tikitaka/triptroop/user/domain/entity/User.java, src/main/java/com/tikitaka/triptroop/user/domain/repository/ProfileRepository.java, src/main/java/com/tikitaka/triptroop/user/dto/response/ProfileResponse.java, src/main/java/com/tikitaka/triptroop/user/dto/response/UserDetailResponse.java, src/main/java/com/tikitaka/triptroop/user/dto/response/UserProfileResponse.java, src/main/java/com/tikitaka/triptroop/user/dto/response/UserResponse.java, src/main/java/com/tikitaka/triptroop/user/service/ProfileService.java, src/main/java/com/tikitaka/triptroop/user/service/UserService.java, src/test/java/com/tikitaka/triptroop/user/service/ProfileServiceTest.java, src/test/java/com/tikitaka/triptroop/user/service/UserServiceTest.java
> 로그아웃, 유저 정보 및 프로필 조회
- #69, #70
- 로그인 실패 예외 변경
- 로그아웃 기능 구현
- 회원 정보 조회 기능 구현
- `UserProfileResponse`  추가:  회원 프로필 정보, 나이 구간, 성별, 고도, 닉네임, 프로필이미지, 설명, mbti
=> #69, #70 로그아웃, 유저 정보 및 프로필 조회

src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java, src/main/java/com/tikitaka/triptroop/schedule/domain/entity/Schedule.java, src/main/java/com/tikitaka/triptroop/schedule/domain/entity/ScheduleItem.java, src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
> 일정 , 계획 삭제 기능
- closed #102 
- 일정 , 계획 삭제 기능
- 삭제 시 is_deleted = 1로 변경
=> #102 일정 계획 삭제 기능 완료

src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java, src/main/java/com/tikitaka/triptroop/schedule/domain/entity/ScheduleItem.java, src/main/java/com/tikitaka/triptroop/schedule/domain/entity/ScheduleParticipant.java, src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleParticipantAcceptRequest.java, src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleParticipantRejectedRequest.java, src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleParticipantRequest.java, src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleParticipantService.java
> 일정 신청 승인 반려
- closed #104 
- 일정 신청 기능과 신청이 들어왔을시 승인 또는 반려 할  수 있는 기능
=> #104 일정 신청 승인 반려 기능

src/main/java/com/tikitaka/triptroop/common/exception/ForbiddenException.java, src/main/java/com/tikitaka/triptroop/common/exception/type/ExceptionCode.java, src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java, src/main/java/com/tikitaka/triptroop/schedule/domain/entity/Schedule.java, src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleItemRepository.java, src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepository.java, src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepositoryCustom.java, src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepositoryImpl.java, src/main/java/com/tikitaka/triptroop/schedule/dto/response/ScheduleDetailResponse.java, src/main/java/com/tikitaka/triptroop/schedule/dto/response/ScheduleInformationResponse.java, src/main/java/com/tikitaka/triptroop/schedule/dto/response/ScheduleItemInfoResponse.java, src/main/java/com/tikitaka/triptroop/schedule/dto/response/ScheduleParticipantProfileResponse.java, src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
- [x} 의존성, 환경 변수, 빌드 관련 코드 업데이트
> 일정 상세 조회 코드 리펙토링
- closed #107 
상세 조회문 코드 query dsl로 변경 후 
게시글 수정 시 로그인한 유저와 작성한 유저가 동일한 경우에만 가능하게 구현
=> #107 일정 상세 조회문 코드 수정

src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java, src/main/java/com/tikitaka/triptroop/schedule/domain/entity/Schedule.java, src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepositoryImpl.java, src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
> 일정 공개여부 변경 구현
- closed #110 
- 일정 공개여부를 status 파라미터 값에 따라 변경하는 로직
=> #110 일정 공개여부 변경 구현

src/main/java/com/tikitaka/triptroop/common/exception/ForbiddenException.java, src/main/java/com/tikitaka/triptroop/common/exception/type/ExceptionCode.java, src/main/java/com/tikitaka/triptroop/travel/controller/TravelCommentController.java, src/main/java/com/tikitaka/triptroop/travel/controller/TravelController.java, src/main/java/com/tikitaka/triptroop/travel/domain/entity/Travel.java, src/main/java/com/tikitaka/triptroop/travel/domain/entity/TravelComment.java, src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelCommentRepository.java, src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelRepository.java, src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelRepositoryCustom.java, src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelRepositoryImpl.java, src/main/java/com/tikitaka/triptroop/travel/dto/request/TravelCommentUpdateRequest.java, src/main/java/com/tikitaka/triptroop/travel/dto/response/ImageTravelResponse.java, src/main/java/com/tikitaka/triptroop/travel/dto/response/TravelDetailResponse.java, src/main/java/com/tikitaka/triptroop/travel/dto/response/TravelInfoResponse.java, src/main/java/com/tikitaka/triptroop/travel/dto/response/TravelResponse.java, src/main/java/com/tikitaka/triptroop/travel/service/TravelCommentService.java, src/main/java/com/tikitaka/triptroop/travel/service/TravelService.java
- closed #92 
- 여행지 소개 상세조회 로직변경 및 
- 등록 ,수정, 삭제 유저 검사 진행
=> #92 여행지 소개 상세 조회 로직변경 및 등록,수정,삭제 로직변경 

src/main/java/com/tikitaka/triptroop/common/exception/type/ExceptionCode.java, src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java, src/main/java/com/tikitaka/triptroop/schedule/domain/entity/Schedule.java, src/main/java/com/tikitaka/triptroop/schedule/domain/entity/ScheduleItem.java, src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleParticipantRepository.java, src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleParticipantService.java, src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
>  신청 시 날짜 , 인원수 조건 충족 해야만 신청가능
- closed #113 
>  신청 시 날짜 , 인원수 조건 충족 해야만 신청가능
=> #113 일정 신청 유효성 검사 로직 추가

src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java, src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleParticipantService.java
> 리턴 값 변경
- closed #134
- 리턴 값 변경
=> #134 리턴 값 변경

src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java, src/main/java/com/tikitaka/triptroop/schedule/domain/entity/ScheduleParticipant.java, src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleParticipantRepository.java, src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleReviewRequest.java, src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleParticipantService.java
> 일정 리뷰 등록 수정 삭제
- closed #118 
- 일정 CRUD 기능
=> #118 일정 리뷰 CRUD

src/main/java/com/tikitaka/triptroop/common/exception/type/ExceptionCode.java, src/main/java/com/tikitaka/triptroop/image/dto/response/ImageResponse.java, src/main/java/com/tikitaka/triptroop/travel/controller/TravelCommentController.java, src/main/java/com/tikitaka/triptroop/travel/controller/TravelController.java, src/main/java/com/tikitaka/triptroop/travel/domain/entity/Travel.java, src/main/java/com/tikitaka/triptroop/travel/domain/entity/TravelComment.java, src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelCommentRepository.java, src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelRepositoryCustom.java, src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelRepositoryImpl.java, src/main/java/com/tikitaka/triptroop/travel/dto/request/TravelCommentRequest.java, src/main/java/com/tikitaka/triptroop/travel/dto/request/TravelRequest.java, src/main/java/com/tikitaka/triptroop/travel/dto/request/TravelUpdateRequest.java, src/main/java/com/tikitaka/triptroop/travel/dto/response/TravelInfoResponse.java, src/main/java/com/tikitaka/triptroop/travel/service/TravelCommentService.java, src/main/java/com/tikitaka/triptroop/travel/service/TravelService.java
-  #115 
- 여행지 소개 상태 변경 비공개 공개 처리
=> #115 여행지 소개 상태 변경 

src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java, src/main/java/com/tikitaka/triptroop/user/controller/AuthController.java, src/main/java/com/tikitaka/triptroop/user/controller/ProfileController.java, src/main/java/com/tikitaka/triptroop/user/controller/UserController.java, src/main/java/com/tikitaka/triptroop/user/domain/entity/User.java, src/main/java/com/tikitaka/triptroop/user/service/ProfileService.java
> Security 설정 변경 및 회원 탈퇴 로직 수정 
- closed #145 
- 회원 탈퇴 시 탈퇴일자 추가
- Controller 응답 메시지 수정
- Spring Security 설정 수정:
- hasRole -> hasAuthority
- CORS 허용 주소 추가
=> #145 Security 설정 변경 및 회원 탈퇴 로직 수정 

src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java
> 로그아웃 경로 security 허용 경로 추가
- closed #149
- SecurityConfig 수정
=> #149 로그아웃 경로 security 허용 경로 추가

src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java, src/main/java/com/tikitaka/triptroop/common/exception/AuthException.java, src/main/java/com/tikitaka/triptroop/common/exception/handler/GeneralExceptionHandler.java, src/main/java/com/tikitaka/triptroop/common/security/filter/JwtAuthenticationFilter.java, src/main/java/com/tikitaka/triptroop/common/security/util/TokenUtils.java, src/main/java/com/tikitaka/triptroop/user/controller/AuthController.java, src/main/java/com/tikitaka/triptroop/user/domain/entity/User.java, src/main/java/com/tikitaka/triptroop/user/service/AuthService.java
> Acess Token 재발급
- closed #158
- `Refresh Token`으로 `Access Token` 재발급 기능
- `AuthException` 추가: 인증/인가 관련 예외 처리용
- SecurityConfig 수정:
- `/token/issue` 허용 경로에 추가
- `/logout` 허용 경로에서 삭제
- 일부 코드 리팩터링
=> #158 Acess Token 재발급

src/main/java/com/tikitaka/triptroop/common/dto/response/ApiResponse.java, src/main/java/com/tikitaka/triptroop/common/exception/handler/GeneralExceptionHandler.java, src/main/java/com/tikitaka/triptroop/user/dto/request/SignUpRequest.java, src/main/java/com/tikitaka/triptroop/user/service/UserService.java
- closed #{이슈번호}
- SignUpRequest 수정
- `@NotBlank` : `{필드명}은 필수 항목입니다.` 
- `@Pattern`
- 이름: 2자 이상, 한글
- 생년월일: 8자의 숫자만 포함
- 성별: F, M 만 포함 가능
- MethodArgumentNotValidException 응답 형식 변경 (`@Valid`)  
- 프론트에서 좀 더 명확한 데이터를 받기 위해 수정
- 변경 전
```
{
"success": false,
"message": null,
"result": {
"code": 400,
"message": "공백일 수 없습니다"
}
}
```
- 변경 후
```
{
"success": false,
"message": "Validation Error!",
"result": {
"password": "8-20자 이내로 입력해주세요.",
"gender": "성별의 형식이 올바르지 않습니다. (ex. 여자-F/남자-M)",
"name": "이름의 형식이 올바르지 않습니다.",
"birth": "생년월일의 형식이 올바르지 않습니다. (ex. 19900101)"
}
}
```
=> #160 회원 가입 검증 메시지 추가 및 @Valid 응답 형식 변경

src/main/java/com/tikitaka/triptroop/common/security/handler/LoginSuccessHandler.java, src/main/java/com/tikitaka/triptroop/user/domain/repository/UserRepository.java, src/main/java/com/tikitaka/triptroop/user/service/AuthService.java, src/test/java/com/tikitaka/triptroop/user/service/UserServiceTest.java
> 로그인 시 RefreshToken 유효성 검증
- closed #174 
- LoginSuccessHandler 수정
- 리프레시 토큰이 없거나, 유효하지 않은 경우에만 재발급
- 이메일로 RefreshToken 조회 추가
📚 참고
=> #174 로그인 시 RefreshToken 유효성 검증

.github/workflows/deploy.yml, Dockerfile, build.gradle
> CI/CD 설정 수정 
- closed #188 
- 서브모듈 수정 사항
- `application*.yml` 수정
- redis 폴더 삭제
- `insert.sql` 수정 (users, profiles)
- `docker-compose.yml` 수정
- `Dockerfile` 수정
- `build.gradle` 수정 (copyPrivate 관련)
=> #188 CI/CD 설정 수정 

src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java, src/main/java/com/tikitaka/triptroop/common/email/controller/EmailController.java, src/main/java/com/tikitaka/triptroop/user/controller/AuthController.java, src/main/java/com/tikitaka/triptroop/user/controller/ProfileController.java, src/main/java/com/tikitaka/triptroop/user/controller/UserController.java, src/main/java/com/tikitaka/triptroop/user/domain/repository/ProfileRepository.java, src/main/java/com/tikitaka/triptroop/user/dto/response/CurrentUserResponse.java, src/main/java/com/tikitaka/triptroop/user/service/ProfileService.java, src/main/java/com/tikitaka/triptroop/user/service/UserService.java
> 프론트엔드 관련 변경 및 리팩터링
- closed #194 
- 회원, 프로필, 이메일 관련 리팩터링 및 추가 메서드
- 비밀번호 재설정 기능
=> #194 프론트엔드 관련 변경 및 리팩터링

src/main/java/com/tikitaka/triptroop/admin/controller/AdminNoticeController.java, src/main/java/com/tikitaka/triptroop/admin/domain/repository/AdminNoticeRepository.java, src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminNoticeDetailResponse.java, src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminNoticeResponse.java, src/main/java/com/tikitaka/triptroop/admin/service/AdminNoticeService.java, src/main/java/com/tikitaka/triptroop/notice/domain/entity/Notice.java, src/main/java/com/tikitaka/triptroop/notice/domain/type/NoticeKind.java, src/main/java/com/tikitaka/triptroop/notice/domain/type/NoticeStatus.java
- closed #136 
- 추가된 내용 또는 변경 사항에 대한 상세내역을 작성해주세요.
[Method / url] http://localhost:8080/api/v1/admin/notice
[Request]
├─ [Method / url] : [GET] http://localhost:8080/api/v1/admin/notice
├─ [Header - type / value] :  application / json
└─ [Parameter - name / type / info] : -
[Response]
├─ [Header - type / value] : application / json
├─ [Parameter - name / type / info] : - 
└─ [Success Data Example - success / message / data] :
{
"success": true,
"message": "공지 목록 조회에 성공하였습니다.",
"result": [
{
"id": 1,
"kind": "NORMAL",
"isRead": "0",
"title": "일반 공지 테스트 제목임",
"content": "일반 공지 내용 테스트 내용임",
"status": "TODO",
"createdAt": "2024-06-15T05:31:43",
"modifiedAt": null,
"deliveredAt": null
},
{
"id": 2,
"kind": "EVENT",
"isRead": "0",
"title": "일반 공지 테스트 제목임",
"content": "일반 공지 내용 …
=> /#136 관리자 > 공지 관리 > 공지 목록 조회

src/main/java/com/tikitaka/triptroop/admin/controller/AdminReportController.java, src/main/java/com/tikitaka/triptroop/admin/domain/repository/AdminReportRepository.java, src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminReportDetailResponse.java, src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminReportResponse.java, src/main/java/com/tikitaka/triptroop/admin/service/AdminCategoryService.java, src/main/java/com/tikitaka/triptroop/admin/service/AdminReportService.java
- closed #100 
- 추가된 내용 또는 변경 사항에 대한 상세내역을 작성해주세요.
[Method / url] http://localhost:8080/api/v1/admin/report
[Request]
├─ [Method / url] : [GET] http://localhost:8080/api/v1/admin/report
├─ [Header - type / value] :  application / json
└─ [Parameter - name / type / info] : -
[Response]
├─ [Header - type / value] : application / json
├─ [Parameter - name / type / info] : - 
└─ [Success Data Example - success / message / data] :
{
"success": true,
"message": "신고 목록 조회에 성공하였습니다.",
"result": [
{
"reportId": 1,
"reporterId": 6,
"name": "ddalla11",
"kind": "USER",
"kindReportId": 7,
"targetName": "leok123",
"type": "PROFANITY",
"reportedAt": "2024-06-15 05:31:43",
"status": "REQUESTED"
},
{
"reportId": 2,
"reporterId": 7,
"name": "leok123",
"kind": "COMPANION",
"kindReportId": …
=> #100 관리자 > 신고 관리 > 신고 목록 조회 완료

src/main/java/com/tikitaka/triptroop/user/domain/entity/Profile.java, src/main/java/com/tikitaka/triptroop/user/service/ProfileService.java
> 닉네임 중복 검사 로직 수정
- closed #219
💻 작업 내용
- 수정 시 현재 닉네임과 동일하다면 중복 처리X
=> #219 닉네임 중복 검사 로직 수정

src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java, src/main/java/com/tikitaka/triptroop/user/domain/entity/Profile.java, src/main/java/com/tikitaka/triptroop/user/service/ProfileService.java
> HTTPS 적용 관련 SecurityConfig 수정
- HTTPS 를 적용한 도메인을 SecurityConfig 에 추가함
=> HTTPS 적용 관련 SecurityConfig 수정

src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java
Reverts 2024-TikiTaka/be-triptroop#222
=> Revert "HTTPS 적용 관련 SecurityConfig 수정"

build.gradle, src/main/java/com/tikitaka/triptroop/admin/service/AdminNoticeService.java, src/main/java/com/tikitaka/triptroop/common/config/S3Config.java, src/main/java/com/tikitaka/triptroop/image/service/ImageService.java, src/main/java/com/tikitaka/triptroop/image/service/LocalStorageService.java, src/main/java/com/tikitaka/triptroop/image/service/S3StorageService.java, src/main/java/com/tikitaka/triptroop/image/util/FileUploadUtils.java, src/main/java/com/tikitaka/triptroop/report/service/ReportService.java, src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java, src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java, src/main/java/com/tikitaka/triptroop/travel/controller/TravelController.java, src/main/java/com/tikitaka/triptroop/user/controller/ProfileController.java, src/main/java/com/tikitaka/triptroop/user/service/ProfileService.java
>  이미지 업로드 로직 분리(Local, S3)
- closed #225
- `build.gradle` 에 aws-s3 의존성 추가
- `application-prod.yml`에 s3 설정 추가
- 이미지 업로드 로직 분리 (Local, S3)
- `ImageService` 인터페이스로 변경
- `ImageStorageService`, `S3ImageStorageService` 구현체 추가
- 로컬 환경: `ImageStorageService` 및 application.yml 
- 배포 환경: `S3ImageStorageService` 및 application-prod.yml
- 그 외 컨트롤러, 서비스 리팩터링
=> #225 이미지 업로드 로직 분리(Local, S3)

README.md
> README.md 수정
- closed #217
- README.md 수정
=> #217 README 수정
